# Generated by Django 2.0 on 2018-09-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20180911_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='book_file',
            field=models.FileField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_image',
            field=models.ImageField(upload_to='pictures'),
        ),
    ]
