# Generated by Django 2.0 on 2018-09-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20180911_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='book_file',
            field=models.FileField(upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_image',
            field=models.ImageField(upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
