# Generated by Django 2.0 on 2018-09-12 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_bookdetail_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetail',
            name='user',
        ),
    ]
