# Generated by Django 2.0 on 2018-09-17 08:44

from django.db import migrations
import slugger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_remove_bookdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='slug',
            field=slugger.fields.AutoSlugField(blank=True, null=True, populate_from='title'),
        ),
    ]
